"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { collection,doc,getDoc,getDocs,query,where } from "firebase/firestore";
import { db } from "@/lib/firebase-client";
import { useAuth } from "@/components/AuthProvider";
import LocationPanel from "@/components/LocationPanel";
import QuestionsSection from "@/components/QuestionsSection";
import ReservationForm from "@/components/ReservationForm";
import ProfileSummary from "@/components/ProfileSummary";
import StarRating from "@/components/StarRating";
import { formatPricing } from "@/lib/format";
export default function OrganDetailClient({id,initialOrgan=null}){
  const {user}=useAuth();const [organ,setOrgan]=useState(initialOrgan);const [loading,setLoading]=useState(!initialOrgan);const [ownerProfile,setOwnerProfile]=useState(null);const [ownerContact,setOwnerContact]=useState(null);const [reviews,setReviews]=useState([]);
  useEffect(()=>{if(!db||!id){setLoading(false);return;}getDoc(doc(db,"organs",id)).then((snap)=>setOrgan(snap.exists()?{id:snap.id,...snap.data()}:null)).catch(()=>setOrgan(null)).finally(()=>setLoading(false));},[id]);
  useEffect(()=>{if(!db||!organ?.ownerId)return;Promise.all([getDoc(doc(db,"profiles",organ.ownerId)),getDoc(doc(db,"publicContacts",organ.ownerId)).catch(()=>null)]).then(([p,c])=>{setOwnerProfile(p?.exists()?p.data():null);setOwnerContact(c?.exists()?c.data():null);});},[organ?.ownerId,user?.uid]);
  useEffect(()=>{if(!db||!id)return;getDocs(query(collection(db,"organReviews"),where("organId","==",id))).then((snap)=>setReviews(snap.docs.map((item)=>({id:item.id,...item.data()})))).catch(()=>{});},[id]);
  const average=useMemo(()=>reviews.length?reviews.reduce((sum,r)=>sum+Number(r.rating||0),0)/reviews.length:0,[reviews]);
  if(loading)return <section className="section"><div className="container"><div className="skeleton"/></div></section>;
  if(!organ)return <section className="section"><div className="container empty-state"><h1>Organ not found</h1><p>This listing may have been removed or is not public.</p></div></section>;
  const unclaimed=organ.listingOwnership==="unclaimed";const jsonLd={"@context":"https://schema.org","@type":"Place",name:organ.name,description:organ.description,address:organ.location?.formattedAddress,geo:organ.location?.latitude?{"@type":"GeoCoordinates",latitude:organ.location.latitude,longitude:organ.location.longitude}:undefined};
  return <section className="section"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><div className="container detail-grid"><div className="stack-lg">{organ.imageUrl&&<img className="detail-image" src={organ.imageUrl} alt=""/>}<div>{unclaimed&&<strong className="unclaimed-badge large">UNCLAIMED LISTING</strong>}<span className="eyebrow">{organ.location?.city||"Pipe organ"}</span><h1>{organ.name}</h1><p className="lead">{organ.organizationName}</p></div>{unclaimed&&<article className="unclaimed-notice"><h2>Public reference listing</h2><p>This organ was added from a public source and has not been claimed by its organization. Practice requests, payments, reviews, and Q&amp;A are disabled until ownership is verified.</p><Link className="button" href={`/claim/${id}`}>Claim this listing</Link>{organ.source?.url&&<p className="small">Source: <a href={organ.source.url} target="_blank" rel="noreferrer">Pipe Organ Database</a></p>}</article>}<article className="card stack"><div className="grid-3"><div><span className="small muted">Builder</span><strong>{organ.builder||"Not listed"}</strong></div><div><span className="small muted">Year</span><strong>{organ.year||"Not listed"}</strong></div><div><span className="small muted">Size</span><strong>{organ.manuals?`${organ.manuals} manuals`:"Not listed"}{organ.stops?` · ${organ.stops} stops`:""}</strong></div></div><p>{organ.description}</p>{organ.publicAccessNotes&&<div className="message"><strong>Public access notes:</strong> {organ.publicAccessNotes}</div>}<div className="pricing-banner"><strong>{formatPricing(organ.pricing)}</strong>{organ.pricing?.instructions&&<span>{organ.pricing.instructions}</span>}</div></article><LocationPanel location={organ.location}/><section className="card stack-lg"><div><span className="eyebrow">Verified sessions</span><h2>{reviews.length?`${average.toFixed(1)} / 5 from ${reviews.length} review${reviews.length===1?"":"s"}`:"No reviews yet"}</h2></div>{reviews.map((review)=><article className="review-card" key={review.id}><StarRating value={review.rating} readOnly/><p>{review.comment||"No written comment."}</p></article>)}</section><QuestionsSection targetType="organ" targetId={id} ownerId={organ.ownerId} enabled={!unclaimed}/></div><aside className="detail-sidebar stack-lg">{!unclaimed&&<article className="card"><span className="eyebrow">Managed by</span><ProfileSummary profile={ownerProfile} userId={organ.ownerId} contact={ownerContact}/></article>}{!unclaimed&&organ.bookingEnabled&&organ.ownerId!==user?.uid&&<ReservationForm organ={organ}/>} {!unclaimed&&!organ.bookingEnabled&&<article className="card"><h2>Requests unavailable</h2><p className="muted">This organization is not currently accepting practice requests for this instrument.</p></article>}</aside></div></section>;
}
