"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { addDoc,collection,getDocs,query,serverTimestamp,where } from "firebase/firestore";
import { db } from "@/lib/firebase-client";
import { useAuth } from "@/components/AuthProvider";
export default function QuestionsSection({targetType,targetId,ownerId,enabled=true}){
  const {user,account,profile}=useAuth();const [questions,setQuestions]=useState([]);const [question,setQuestion]=useState("");const [message,setMessage]=useState("");const [working,setWorking]=useState(false);
  async function load(){if(!db||!targetId)return;const queries=[getDocs(query(collection(db,"questions"),where("targetId","==",targetId),where("status","==","answered")))];if(user?.uid)queries.push(getDocs(query(collection(db,"questions"),where("askerId","==",user.uid))));if(user?.uid===ownerId)queries.push(getDocs(query(collection(db,"questions"),where("ownerId","==",user.uid))));const snapshots=await Promise.all(queries);const unique=new Map();for(const snap of snapshots)for(const item of snap.docs){const data={id:item.id,...item.data()};if(data.targetId===targetId)unique.set(item.id,data);}setQuestions([...unique.values()]);}
  useEffect(()=>{load().catch(()=>{});},[targetId,user?.uid]);
  async function submit(event){event.preventDefault();if(!user)return setMessage("Sign in to ask a question.");if(account?.role!=="organist")return setMessage("Questions are submitted from organist accounts.");if(!enabled)return setMessage("Questions are unavailable for this listing.");if(question.trim().length<5)return setMessage("Write a more specific question.");setWorking(true);try{await addDoc(collection(db,"questions"),{targetType,targetId,ownerId,askerId:user.uid,askerName:profile?.displayName||user.displayName||"OpenOrgan user",question:question.trim(),answer:"",status:"open",readByAsker:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});setQuestion("");setMessage("Question sent.");await load();}catch(error){setMessage(error.message||"Unable to send the question.");}finally{setWorking(false);}}
  return <section className="card stack-lg"><div><span className="eyebrow">Questions and answers</span><h2>Ask the host</h2></div>{questions.filter((item)=>item.status==="answered").map((item)=><article className="question-card" key={item.id}><p><strong>{item.askerName}:</strong> {item.question}</p><div className="question-answer">{item.answer}</div></article>)}{enabled?<form className="stack" onSubmit={submit}><label>Your question<textarea value={question} onChange={(e)=>setQuestion(e.target.value)} placeholder="Ask about access, availability, the instrument, or the event."/></label><button className="button" disabled={working}>{working?"Sending...":"Ask Question"}</button></form>:<div className="message warning">Q&amp;A becomes available after this listing is claimed and published.</div>}{message&&<div className="message">{message}</div>}{!user&&<p className="muted"><Link href={`/login?next=/${targetType==="organ"?"organs":"events"}/${targetId}`}>Sign in</Link> to ask a question.</p>}</section>;
}
