"use client";
import { toUserMessage } from "@/lib/user-error";
import { useState } from "react";
import { addDoc,collection,serverTimestamp,Timestamp } from "firebase/firestore";
import { useRouter } from "next/navigation";
import { db } from "@/lib/firebase-client";
import { useAuth } from "@/components/AuthProvider";
export default function ReservationForm({organ}){
  const router=useRouter();const {user,account,profile}=useAuth();const [form,setForm]=useState({date:"",startTime:"",endTime:"",purpose:""});const [message,setMessage]=useState("");const [working,setWorking]=useState(false);
  function change(event){setForm({...form,[event.target.name]:event.target.value});}
  async function submit(event){event.preventDefault();if(!user)return router.push(`/login?next=/organs/${organ.id}`);if(account?.role!=="organist")return setMessage("Practice requests require an organist account.");if(!organ.bookingEnabled||organ.listingOwnership!=="claimed")return setMessage("This organ is not accepting practice requests.");const start=new Date(`${form.date}T${form.startTime}`);const end=new Date(`${form.date}T${form.endTime}`);if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||start<=new Date()||end<=start)return setMessage("Choose a future session with an end time after its start.");setWorking(true);try{await addDoc(collection(db,"reservations"),{userId:user.uid,userName:profile?.displayName||user.displayName||"OpenOrgan user",organId:organ.id,organName:organ.name,organizationOwnerId:organ.ownerId,organizationName:organ.organizationName,date:form.date,startTime:form.startTime,endTime:form.endTime,startDateTime:Timestamp.fromDate(start),endDateTime:Timestamp.fromDate(end),purpose:form.purpose.trim(),status:"pending",decisionNote:"",pricingSnapshot:organ.pricing||{model:"free",amountCents:0,currency:"USD",paymentMethods:[],paymentTiming:"",instructions:""},createdAt:serverTimestamp(),updatedAt:serverTimestamp()});router.push("/dashboard");}catch(error){setMessage(toUserMessage(error, "Unable to submit the request."));}finally{setWorking(false);}}
  return <form className="card stack" onSubmit={submit}><span className="eyebrow">Practice access</span><h2>Request a session</h2><div className="form-grid"><label>Date<input name="date" type="date" value={form.date} onChange={change} required/></label><label>Start<input name="startTime" type="time" value={form.startTime} onChange={change} required/></label></div><label>End<input name="endTime" type="time" value={form.endTime} onChange={change} required/></label><label>What will you practice?<textarea name="purpose" value={form.purpose} onChange={change} required/></label><button className="button" disabled={working}>{working?"Sending...":"Request Practice Access"}</button>{message&&<div className="message error">{message}</div>}</form>;
}
