"use client";
import dynamic from "next/dynamic";
import { useCallback, useEffect, useMemo, useState } from "react";
import { collection, getDocs, query, where } from "firebase/firestore";
import { db } from "@/lib/firebase-client";
import OrganCard from "@/components/OrganCard";
import { toDate } from "@/lib/format";
const SearchMap = dynamic(() => import("@/components/SearchMap"), { ssr: false, loading: () => <div className="skeleton map-shell" /> });
function price(organ) { return organ.pricing?.model === "free" ? 0 : Number(organ.pricing?.amountCents || 0); }
function score(organ, routes) { const rating = Number(organ.ratingAverage || 0) / 5; const cost = 1 - Math.min(price(organ) / 10000, 1); const reliability = Number(organ.providerReliability || .8); const distance = routes && Number.isFinite(organ.routeDistanceMeters) ? 1 - Math.min(organ.routeDistanceMeters / 80467.2, 1) : null; return distance == null ? rating * .643 + cost * .286 + reliability * .071 : rating * .45 + distance * .3 + cost * .2 + reliability * .05; }
export default function SearchExperience() {
  const [organs,setOrgans]=useState([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [search,setSearch]=useState(""); const [sort,setSort]=useState("recommended"); const [selectedId,setSelectedId]=useState(""); const [view,setView]=useState("list"); const [routing,setRouting]=useState(false);
  const selectFromMap = useCallback((id) => { setSelectedId(id); document.getElementById(`organ-card-${id}`)?.scrollIntoView({ behavior:"smooth", block:"center" }); }, []);
  useEffect(() => { if (!db) { setLoading(false); return; } Promise.all([getDocs(query(collection(db,"organs"),where("status","==","active"))),getDocs(collection(db,"organReviews"))]).then(([organSnap,reviewSnap]) => { const grouped=new Map(); reviewSnap.docs.forEach((item)=>{const r=item.data(); if(!grouped.has(r.organId)) grouped.set(r.organId,[]); grouped.get(r.organId).push(Number(r.rating||0));}); setOrgans(organSnap.docs.map((item)=>{const data=item.data();const values=grouped.get(item.id)||[];return{id:item.id,...data,ratingAverage:values.length?values.reduce((a,b)=>a+b,0)/values.length:0,ratingCount:values.length};})); }).catch((error)=>setMessage(error.message||"Unable to load organs.")).finally(()=>setLoading(false)); },[]);
  async function loadRoutes(){if(!navigator.geolocation)return setMessage("Your browser does not support location access.");setRouting(true);setMessage("");navigator.geolocation.getCurrentPosition(async(position)=>{try{const destinations=organs.filter((o)=>o.location?.placeId).map((o)=>({id:o.id,placeId:o.location.placeId}));const response=await fetch("/api/routes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({origin:{latitude:position.coords.latitude,longitude:position.coords.longitude},destinations})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to load routes.");const results=new Map(data.results.map((r)=>[r.id,r]));setOrgans((current)=>current.map((o)=>({...o,...results.get(o.id)})));setMessage("Ranking now uses Google route distances.");}catch(error){setMessage(error.message||"Unable to load route distances.");}finally{setRouting(false);}},()=>{setRouting(false);setMessage("Location permission was not granted.");},{timeout:10000,maximumAge:300000});}
  const filtered=useMemo(()=>{const term=search.trim().toLowerCase();const routes=organs.some((o)=>Number.isFinite(o.routeDistanceMeters));const items=organs.filter((o)=>!term||[o.name,o.organizationName,o.builder,o.location?.city,o.location?.region].filter(Boolean).join(" ").toLowerCase().includes(term));items.sort((a,b)=>{if(sort==="newest")return(toDate(b.createdAt)?.getTime()||0)-(toDate(a.createdAt)?.getTime()||0);if(sort==="distance")return(a.routeDistanceMeters??Infinity)-(b.routeDistanceMeters??Infinity);if(sort==="rating")return(b.ratingAverage||0)-(a.ratingAverage||0);if(sort==="price")return price(a)-price(b);return score(b,routes)-score(a,routes);});return items;},[organs,search,sort]);
  return <div className="search-layout"><section className={`search-list-panel ${view==="map"?"mobile-hidden":""}`}><div className="page-header compact"><span className="eyebrow">Greater Boston first</span><h1>Find organs</h1><p>Claimed practice listings and clearly marked public reference listings.</p></div><div className="mobile-view-toggle"><button className="button" onClick={()=>setView("list")}>List</button><button className="button-secondary" onClick={()=>setView("map")}>Map</button></div><div className="search-toolbar"><input aria-label="Search organs" placeholder="Church, city, builder..." value={search} onChange={(e)=>setSearch(e.target.value)}/><select aria-label="Order organs" value={sort} onChange={(e)=>setSort(e.target.value)}><option value="recommended">Recommended</option><option value="distance">Distance</option><option value="rating">Highest rated</option><option value="price">Lowest cost</option><option value="newest">Newest listing</option></select></div><div className="form-actions"><button className="button-secondary" onClick={loadRoutes} disabled={routing||!organs.length}>{routing?"Loading Routes...":"Use My Location for Ranking"}</button></div>{message&&<div className="message">{message}</div>}{loading?<div className="skeleton"/>:filtered.length?<div className="stack">{filtered.map((organ)=><OrganCard key={organ.id} organ={organ} selected={selectedId===organ.id} onHover={setSelectedId}/>)}</div>:<div className="empty-state"><h2>No organs found</h2></div>}</section><aside className={`search-map-panel ${view==="list"?"mobile-hidden":""}`}><div className="mobile-view-toggle"><button className="button-secondary" onClick={()=>setView("list")}>List</button><button className="button" onClick={()=>setView("map")}>Map</button></div><SearchMap organs={filtered} selectedId={selectedId} onSelect={selectFromMap}/></aside></div>;
}
