import crypto from "node:crypto";
import { Resend } from "resend";
import { FieldValue,Timestamp } from "firebase-admin/firestore";
import { apiError,requireServerUser } from "@/lib/auth-server";
const PERSONAL=new Set(["gmail.com","yahoo.com","outlook.com","hotmail.com","icloud.com","aol.com","proton.me","protonmail.com"]);
function host(value){try{return new URL(value).hostname.toLowerCase().replace(/^www\./,"");}catch{return "";}}
function mailHost(value){return String(value).trim().toLowerCase().split("@")[1]||"";}
function related(a,b){return a===b||a.endsWith(`.${b}`)||b.endsWith(`.${a}`);}
export async function POST(request){try{const{decoded,account,db}=await requireServerUser(request);if(account?.role!=="organization")throw Object.assign(new Error("Organization account required."),{status:403});const{website,email}=await request.json();const websiteDomain=host(website);const emailDomain=mailHost(email);if(!websiteDomain||!emailDomain)throw Object.assign(new Error("Enter a valid HTTPS website and email."),{status:400});if(!String(website).startsWith("https://")&&!String(website).startsWith("http://"))throw Object.assign(new Error("The official website must begin with https:// or http://."),{status:400});if(PERSONAL.has(emailDomain))throw Object.assign(new Error("Use an official organization-domain email, not a personal email service."),{status:400});if(!related(websiteDomain,emailDomain))throw Object.assign(new Error("The email domain must match the official website domain."),{status:400});const requestRef=db.collection("verificationRequests").doc(decoded.uid);const previous=await requestRef.get();if(previous.exists&&previous.data().lastSentAt?.toMillis?.()>Date.now()-60000)throw Object.assign(new Error("Wait one minute before sending another code."),{status:429});const code=String(crypto.randomInt(100000,1000000));const codeHash=crypto.createHash("sha256").update(code).digest("hex");await requestRef.set({userId:decoded.uid,website:String(website).trim(),websiteDomain,email:String(email).trim().toLowerCase(),emailDomain,codeHash,attempts:0,expiresAt:Timestamp.fromMillis(Date.now()+15*60*1000),lastSentAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});const apiKey=process.env.RESEND_API_KEY;if(!apiKey)throw Object.assign(new Error("Resend is not configured."),{status:503});const resend=new Resend(apiKey);const result=await resend.emails.send({from:process.env.VERIFICATION_FROM_EMAIL||"The OpenOrgan Project <verify@openorgan.org>",to:String(email).trim(),subject:"Your OpenOrgan organization verification code",text:`Your verification code is ${code}. It expires in 15 minutes.`,html:`<p>Your verification code is:</p><p style="font-size:32px;font-weight:700;letter-spacing:6px">${code}</p><p>It expires in 15 minutes.</p>`});if(result.error){await requestRef.delete().catch(()=>{});throw new Error(result.error.message||"Unable to send the email.");}await db.collection("users").doc(decoded.uid).update({verificationStatus:"code_sent",verificationEmail:String(email).trim().toLowerCase(),verificationDomain:websiteDomain,updatedAt:FieldValue.serverTimestamp()});return Response.json({message:"Verification code sent."});}catch(error){return apiError(error);}}
